AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'

Layout/LineLength:
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: false
