language: ruby
cache: bundler

rvm:
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile

before_script:
  - psql -c 'create database "trasto-test";' -U postgres
